# Generated by Django 3.2.16 on 2022-11-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dhyy9pzrd/image/upload/v1668202815/m3efn2fnj5y2syaro1lk.jpg', upload_to='images/'),
        ),
    ]
