# Generated by Django 3.2.16 on 2022-11-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../woqnlnpretg5qyrnmwr2', upload_to='images/'),
        ),
    ]
